name: Deploy Java App to EKS using Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image to Docker Hub
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Display URL
      run: |
        kubectl get pods -n github-action-sp
        kubectl get svc -n github-action-sp

    - name: Wait for LoadBalancer and Display Full URL
      run: |
        echo "⏳ Waiting for LoadBalancer IP..."
        sleep 60

        EXTERNAL_IP=$(kubectl get svc java-app-service -n github-action-sp -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
        
        if [ -z "$EXTERNAL_IP" ]; then
          echo "❌ LoadBalancer IP not available yet."
          exit 1
        fi

        echo "✅ Your app is available at: http://$EXTERNAL_IP/hello"
